# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Radio', 'Radio'), ('Select', 'Select'), ('Select-Multiple', 'Select-Multiple'), ('Integer', 'Integer')], default='Text', max_length=20),
        ),
    ]
